### ISSUE TITLE
Minor Questions

### ISSUE THREAD

**Issue by abhigenie92** [keon/policy-gradient#1]
1.  are the weights present in the repo. trained? Asking because they didn't work that well.
2. do you find the approach better than simple feed-forward approach?(http://karpathy.github.io/2016/05/31/rl/)
3. how did you narrow down on architecture?
  a. why only 1 conv. layer?
  b. why not deconv. layers?

Thanks.

**Comment by keon** [comment]
Hey @abhigenie92 ,
1. I don't think it is a trained model. It is just there for the demonstration. But I could train it again since I bought a new computer :)
2. I didn't compare the performances, but CNN should be slightly better if tuned right.
3. I didn't think much while I was making it. It just worked, so I moved on. No particular reason.

The reasons for 1, 2, and 3 are about the same: the training took too long on my old machine. I didn't have time for experimentations.
